// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0JI7QL7AvV8QtoGBTg6mq-6w_uPQQEw',
    appId: '1:652192643451:web:f755abff3c2a345847e5de',
    messagingSenderId: '652192643451',
    projectId: 'image-u-v',
    authDomain: 'image-u-v.firebaseapp.com',
    storageBucket: 'image-u-v.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4k3xs2NA3aRv3l2VfsOPnfDLgU2TW6Y',
    appId: '1:652192643451:android:67632b36bed7029d47e5de',
    messagingSenderId: '652192643451',
    projectId: 'image-u-v',
    storageBucket: 'image-u-v.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPKy4aHVs8m1boaEfHmO3AmutJUFDoUk',
    appId: '1:652192643451:ios:62f7ca7e29b8467447e5de',
    messagingSenderId: '652192643451',
    projectId: 'image-u-v',
    storageBucket: 'image-u-v.firebasestorage.app',
    iosBundleId: 'com.example.otpPageFlutter',
  );
}
