// import 'package:flutter/material.dart';
// import 'screens/mobile_input_page.dart';

// void main() {
//   runApp(const OTPApp());
// }

// class OTPApp extends StatelessWidget {
//   const OTPApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'OTP Verification',
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(primarySwatch: Colors.blue),
//       home: MobileInputPage(),
//     );
//   }
// }

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:otp_page_flutter/firebase_options.dart'; // 👈 this file was generated by `flutterfire configure`
import 'screens/mobile_input_page.dart'; // 👈 your first screen (enter mobile number)

void main() async {
  // Ensures that plugin services are initialized before Firebase is used
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options from firebase_options.dart
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'OTP Verification',
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        scaffoldBackgroundColor: Colors.white,
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
        ),
      ),
      home: const MobileInputPage(), // 👈 Start with the phone input page
    );
  }
}
